[project]
name = "grlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.4.1",
    "tokenizers>=0.22.1",
    "torch>=2.9.1",
]

[tool.setuptools]
py-modules = []
